#You can edit what ever you want, add variables and that stuff
  motd:
    lines:
      - |-
        <gradient:red:blue>ShieldMotd</gradient> <yellow>Lightweight Motd<reset>
        <gradient:#F53803:#FCE043>Full HEX color Support</gradient>
      - <gradient:red:blue>ShieldMotd</gradient> <newline><aqua>Full motd from single line

# Are you having issues with forks that have same checks?
# You can disable them on this simple list by checking the brand
  ignore-proxy:
    - NullCordX
    - XCord
    - FlameCord