#ShieldMotd by xIsm4 - www.shieldcommunity.net

#You can use multiple formats such as MiniMessage, Legacy or RGB
  motd:
    lines:
      - |-
        <gradient:red:blue>ShieldMotd</gradient> <yellow>Lightweight Motd<reset>
        <gradient:#F53803:#FCE043>Full HEX color Support</gradient>
      - <gradient:red:blue>ShieldMotd</gradient> <newline><aqua>Full motd from single line

#Should the motd hide the real count of players on some ping request?
  hide-players: false

#Should the motd set a custom player-information?
  player-info: " <gradient:red:blue>ShieldMotd</gradient>"
  enabled: true

#What name should the MOTD send when receives a ping request
  version-name: "ShieldMotd"
  override-name: false
